### ISSUE TITLE
Allow re-pinning without updating dependencies

### ISSUE THREAD

**Issue by sitaktif** [google/cargo-raze#521] opened 2022-09-08 18:52 UTC
Sometimes, we need to repin our `crates_repository` because changes (ones that do not affect dependency resolution) were made to the repository rule.

One example is adding a `compile_data` annotation:

```
crates_repository(
    [...]
    annotations = {
        "openssl-sys": [
            crate.annotation(
                compile_data = [
                    "@openssl//:gen_dir",
                ],
    [...]
```

It would be great to avoid having to the re-resolve dependencies when that happens.

**Comment by illicitonion** [comment] 2022-09-08 19:01
`crates_repository` is actually a `rules_rust` concept not a `cargo-raze` one :) I think this is a duplicate of https://github.com/bazelbuild/rules_rust/issues/1522 ? tl;dr: It's possible (by setting `CARGO_BAZEL_REPIN=workspace`), but not very discoverable.

**Closed by illicitonion** 2022-09-08 19:01 UTC
